using System.IO.Pipelines;

namespace FirstMyProject.Models
{
    public class DbInitializer
    {
        public static void Seed(IApplicationBuilder applicationBuilder)
        {
            CakeShopDbContext context = applicationBuilder.ApplicationServices.CreateScope().ServiceProvider.GetRequiredService<CakeShopDbContext>();

            if (!context.Categories.Any())
            {
                context.Categories.AddRange(Categories.Select(c => c.Value));
            }

            if (!context.Cakes.Any())
            {
                context.AddRange
                (
                    new Cake { Name = "Caramel Popcorn Cheese Cake", Price = 22.95M, ShortDiscription = "The ultimate cheese cake", LongDiscription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake Cake chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon Cake muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart Cake cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Cheese cakes"], IamgeUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanysCakeshop/cheesecakes/caramelpopcorncheesecake.jpg", InStock = true, IsCakeOfTheWeek = true, IamgeThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanysCakeshop/cheesecakes/caramelpopcorncheesecakesmall.jpg", Information = "" },
                    new Cake { Name = "Chocolate Cheese Cake", Price = 19.95M, ShortDiscription = "The chocolate lover's dream", LongDiscription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake Cake chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon Cake muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart Cake cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Cheese cakes"], IamgeUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanysCakeshop/cheesecakes/chocolatecheesecake.jpg", InStock = true, IsCakeOfTheWeek = true, IamgeThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanysCakeshop/cheesecakes/chocolatecheesecakesmall.jpg", Information = "" },
                    new Cake { Name = "Pistache Cheese Cake", Price = 21.95M, ShortDiscription = "We're going nuts over this one", LongDiscription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake Cake chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon Cake muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart Cake cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Cheese cakes"], IamgeUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanysCakeshop/cheesecakes/pistachecheesecake.jpg", InStock = true, IsCakeOfTheWeek = true, IamgeThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanysCakeshop/cheesecakes/pistachecheesecakesmall.jpg", Information = "" },
                    new Cake { Name = "Pecan Cake", Price = 21.95M, ShortDiscription = "More pecan than you can handle!", LongDiscription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake Cake chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon Cake muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart Cake cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Fruit Cakes"], IamgeUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanysCakeshop/fruitCakes/pecanCake.jpg", InStock = true, IsCakeOfTheWeek = false, IamgeThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanysCakeshop/fruitCakes/pecanCakesmall.jpg", Information = "" },
                    new Cake { Name = "Birthday Cake", Price = 29.95M, ShortDiscription = "A Happy Birthday with this Cake!", LongDiscription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake Cake chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon Cake muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart Cake cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Seasonal Cakes"], IamgeUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanysCakeshop/seasonal/birthdayCake.jpg", InStock = true, IsCakeOfTheWeek = false, IamgeThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanysCakeshop/seasonal/birthdayCakesmall.jpg", Information = "" },
                    new Cake { Name = "Apple Cake", Price = 12.95M, ShortDiscription = "Our famous apple Cakes!", LongDiscription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake Cake chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon Cake muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart Cake cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Fruit Cakes"], IamgeUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/appleCake.jpg", InStock = true, IsCakeOfTheWeek = false, IamgeThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/appleCakesmall.jpg", Information = "" },
                    new Cake { Name = "Blueberry Cheese Cake", Price = 18.95M, ShortDiscription = "You'll love it!", LongDiscription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake Cake chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon Cake muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart Cake cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Cheese cakes"], IamgeUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanysCakeshop/cheesecakes/blueberrycheesecake.jpg", InStock = true, IsCakeOfTheWeek = false, IamgeThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanysCakeshop/cheesecakes/blueberrycheesecakesmall.jpg", Information = "" },
                    new Cake { Name = "Cheese Cake", Price = 18.95M, ShortDiscription = "Plain cheese cake. Plain pleasure.", LongDiscription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake Cake chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon Cake muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart Cake cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Cheese cakes"], IamgeUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanysCakeshop/cheesecakes/cheesecake.jpg", InStock = true, IsCakeOfTheWeek = false, IamgeThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanysCakeshop/cheesecakes/cheesecakesmall.jpg", Information = "" },
                    new Cake { Name = "Cherry Cake", Price = 15.95M, ShortDiscription = "A summer classic!", LongDiscription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake Cake chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon Cake muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart Cake cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Fruit Cakes"], IamgeUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cherryCake.jpg", InStock = true, IsCakeOfTheWeek = false, IamgeThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cherryCakesmall.jpg", Information = "" },
                    new Cake { Name = "Christmas Apple Cake", Price = 13.95M, ShortDiscription = "Happy holidays with this Cake!", LongDiscription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake Cake chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon Cake muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart Cake cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Seasonal Cakes"], IamgeUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/christmasappleCake.jpg", InStock = true, IsCakeOfTheWeek = false, IamgeThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/christmasappleCakesmall.jpg", Information = "" },
                    new Cake { Name = "Cranberry Cake", Price = 17.95M, ShortDiscription = "A Christmas favorite", LongDiscription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake Cake chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon Cake muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart Cake cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Seasonal Cakes"], IamgeUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cranberryCake.jpg", InStock = true, IsCakeOfTheWeek = false, IamgeThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cranberryCakesmall.jpg", Information = "" },
                    new Cake { Name = "Peach Cake", Price = 15.95M, ShortDiscription = "Sweet as peach", LongDiscription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake Cake chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon Cake muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart Cake cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Fruit Cakes"], IamgeUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/peachCake.jpg", InStock = false, IsCakeOfTheWeek = false, IamgeThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/peachCakesmall.jpg", Information = "" },
                    new Cake { Name = "Pumpkin Cake", Price = 12.95M, ShortDiscription = "Our Halloween favorite", LongDiscription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake Cake chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon Cake muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart Cake cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Seasonal Cakes"], IamgeUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/pumpkinCake.jpg", InStock = true, IsCakeOfTheWeek = false, IamgeThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/pumpkinCakesmall.jpg", Information = "" },
                    new Cake { Name = "Rhubarb Cake", Price = 15.95M, ShortDiscription = "My God, so sweet!", LongDiscription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake Cake chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon Cake muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart Cake cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Fruit Cakes"], IamgeUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/rhubarbCake.jpg", InStock = true, IsCakeOfTheWeek = false, IamgeThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/rhubarbCakesmall.jpg", Information = "" },
                    new Cake { Name = "Strawberry Cake", Price = 15.95M, ShortDiscription = "Our delicious strawberry Cake!", LongDiscription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake Cake chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon Cake muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart Cake cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Fruit Cakes"], IamgeUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/strawberryCake.jpg", InStock = true, IsCakeOfTheWeek = false, IamgeThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/strawberryCakesmall.jpg", Information = "" },
                    new Cake { Name = "Strawberry Cheese Cake", Price = 18.95M, ShortDiscription = "You'll love it!", LongDiscription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake Cake chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon Cake muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart Cake cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Cheese cakes"], IamgeUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/strawberrycheesecake.jpg", InStock = false, IsCakeOfTheWeek = false, IamgeThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/strawberrycheesecakesmall.jpg", Information = "" }
                );
            }

            context.SaveChanges();
        }

        private static Dictionary<string, Category>? categories;

        public static Dictionary<string, Category> Categories
        {
            get
            {
                if (categories == null)
                {
                    var genresList = new Category[]
                    {
                        new Category { CategoryName = "Fruit Cakes" },
                        new Category { CategoryName = "Cheese cakes" },
                        new Category { CategoryName = "Seasonal Cakes" }
                    };

                    categories = new Dictionary<string, Category>();

                    foreach (Category genre in genresList)
                    {
                        categories.Add(genre.CategoryName, genre);
                    }
                }

                return categories;
            }
        }
    }
}
